services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results.json:/app/results.json
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5050

  frontend:
    build:
      context: ./frontend/resume-extractor-ui
    ports:
      - "3000:80"
    depends_on:
      - backend



networks:
  resume_net:
    name: resume_net_v2
