services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results.json:/app/results.json
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend/resume-extractor-ui
    ports:
      - "3000:80"
    depends_on:
      - backend



networks:
  resume_net:
    name: resume_net_v2
